const $=s=>document.querySelector(s);const chat=$('#chat'),input=$('#input'),send=$('#sendBtn'),historyEl=$('#history');let messages=[],chats=JSON.parse(localStorage.getItem('router_chats')||'[]'),lastPrompt='';
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderText(text){let x=esc(text);x=x.replace(/```([\s\S]*?)```/g,'<pre>$1</pre>');x=x.replace(/`([^`]+)`/g,'<code>$1</code>');x=x.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');return x}
function addMessage(role,text){$('#welcome')?.remove();const row=document.createElement('div');row.className=`message-row ${role}`;row.innerHTML=`<div class="avatar">${role==='user'?'U':'R'}</div><div><div class="message">${renderText(text)}</div>${role==='assistant'?'<div class="message-actions"><button data-copy>Copy</button><button data-retry>Regenerate</button></div>':''}</div>`;chat.appendChild(row);chat.scrollTop=chat.scrollHeight;return row}
function save(){localStorage.setItem('router_chats',JSON.stringify(chats.slice(-30)))}
function renderHistory(){historyEl.innerHTML='';chats.slice().reverse().forEach((c,i)=>{const b=document.createElement('button');b.className='history-item';b.textContent=c.title;b.onclick=()=>loadChat(chats.length-1-i);historyEl.appendChild(b)})}
function loadChat(i){const c=chats[i];if(!c)return;messages=c.messages.map(x=>({...x}));chat.innerHTML='';messages.forEach(x=>addMessage(x.role,x.content));closeMenu()}
function newChat(){messages=[];chat.innerHTML='<div class="welcome" id="welcome"><div class="welcome-orb">R</div><h1>How can I help?</h1><p>One intelligent interface. Multiple AI providers. Automatic failover.</p><div class="suggestions"><button data-prompt="Explain how an LLM router works in simple terms">Explain an LLM router</button><button data-prompt="Design a production architecture for an AI SaaS">Design an AI SaaS architecture</button><button data-prompt="Write a Python function with tests">Write Python + tests</button><button data-prompt="Analyze the advantages of automatic model failover">Analyze model failover</button></div></div>';bindSuggestions()}
function bindSuggestions(){document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{input.value=b.dataset.prompt;input.dispatchEvent(new Event('input'));input.focus();submit()})}
async function submit(){const text=input.value.trim();if(!text||send.disabled)return;lastPrompt=text;input.value='';resize();messages.push({role:'user',content:text});addMessage('user',text);const row=addMessage('assistant','');const bubble=row.querySelector('.message');send.disabled=true;const started=performance.now();try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages,model:window.selectedModel||null})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Router request failed');const answer=data.choices?.[0]?.message?.content||data.message?.content||data.content||'No response returned.';bubble.innerHTML=renderText(answer);messages.push({role:'assistant',content:answer});$('#latency').textContent=`${Math.round(performance.now()-started)} ms`;if(!chats.length||chats.at(-1).messages.length===0){chats.push({title:text.slice(0,48),messages:[...messages]})}else{chats.at(-1).messages=[...messages]}save();renderHistory()}catch(e){bubble.textContent=`Router error: ${e.message}`;messages.push({role:'assistant',content:bubble.textContent})}finally{send.disabled=false;input.focus()}}
function resize(){input.style.height='auto';input.style.height=Math.min(input.scrollHeight,180)+'px'}function closeMenu(){$('#modelMenu').classList.remove('open');$('#sidebar').classList.remove('open')}
async function status(){try{const r=await fetch('/api/status');const d=await r.json();const pill=$('#statusPill');pill.classList.toggle('ok',true);pill.querySelector('span').textContent=`${d.providers.length} provider${d.providers.length===1?'':'s'} online`;const menu=$('#modelMenu');menu.innerHTML='<button class="model-option" data-model=""><span>Auto Router</span><span>recommended</span></button>';d.providers.forEach(p=>(p.models||[]).forEach(m=>{const b=document.createElement('button');b.className='model-option';b.dataset.model=m;b.innerHTML=`<span>${m}</span><span>${p.name}</span>`;menu.appendChild(b)}));menu.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{window.selectedModel=b.dataset.model;$('#modelName').textContent=b.dataset.model||'Auto Router';closeMenu()});window.routerStatus=d}catch(e){$('#statusPill').querySelector('span').textContent='Offline / configure keys'}}
function settings(){const d=window.routerStatus||{providers:[]};$('#settingsContent').innerHTML=`<div class="provider"><span>Web API</span><small>${location.origin}</small></div>${d.providers.map(p=>`<div class="provider"><span><i class="provider-dot ${p.available?'on':''}"></i>${esc(p.provider)}</span><small>${p.available?'available':'cooldown'} · ${p.day_tokens||0} tokens today</small></div>`).join('')||'<p>No providers configured. Add API keys to .env.</p>'}`;$('#settingsModal').classList.add('open')}
$('#composer').onsubmit=e=>{e.preventDefault();submit()};input.oninput=resize;input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}};$('#newChat').onclick=newChat;$('#clearBtn').onclick=newChat;$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#modelBtn').onclick=()=>$('#modelMenu').classList.toggle('open');$('#settingsBtn').onclick=settings;$('#closeSettings').onclick=()=>$('#settingsModal').classList.remove('open');$('#themeBtn').onclick=()=>{document.documentElement.classList.toggle('light');document.body.classList.toggle('light');};chat.addEventListener('click',e=>{if(e.target.dataset.copy){const t=e.target.closest('.message-row').querySelector('.message').innerText;navigator.clipboard?.writeText(t);e.target.textContent='Copied';setTimeout(()=>e.target.textContent='Copy',1000)}if(e.target.dataset.retry){input.value=lastPrompt;submit()}});bindSuggestions();renderHistory();status();
