const $=s=>document.querySelector(s);const chat=$('#chat'),input=$('#input'),send=$('#sendBtn'),historyEl=$('#history');
let messages=[],chats=[],activeChatId=null,lastPrompt='';const KEY='router_chats_v2';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderText(t=''){let x=esc(t);x=x.replace(/```([\s\S]*?)```/g,'<pre><button class="copy-code" data-copy-code>Copy</button><code>$1</code></pre>');x=x.replace(/`([^`]+)`/g,'<code>$1</code>');x=x.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');return x.replace(/\n/g,'<br>')}
function addMessage(role,text){$('#welcome')?.remove();const r=document.createElement('div');r.className=`message-row ${role}`;r.innerHTML=`<div class="avatar">${role==='user'?'U':'R'}</div><div class="message-col"><div class="message">${renderText(text)}</div>${role==='assistant'?'<div class="message-actions"><button data-copy>Copy</button><button data-retry>Regenerate</button></div>':''}</div>`;chat.appendChild(r);chat.scrollTop=chat.scrollHeight;return r}
function save(){localStorage.setItem(KEY,JSON.stringify(chats.slice(0,30)))}
function renderHistory(){historyEl.innerHTML='';chats.forEach(c=>{const w=document.createElement('div');w.className='history-row';const b=document.createElement('button');b.className='history-item';b.textContent=c.title;b.onclick=()=>loadChat(c.id);const d=document.createElement('button');d.className='history-delete';d.textContent='×';d.onclick=e=>{e.stopPropagation();deleteChat(c.id)};w.append(b,d);historyEl.append(w)})}
function loadChat(id){const c=chats.find(x=>x.id===id);if(!c)return;activeChatId=id;messages=c.messages.map(x=>({...x}));chat.innerHTML='';messages.forEach(x=>addMessage(x.role,x.content));closeMenu()}
function welcome(){return '<div class="welcome" id="welcome"><div class="welcome-orb">R</div><h1>How can I help?</h1><p>One intelligent interface. Multiple AI providers. Automatic failover.</p><div class="suggestions"><button data-prompt="Explain how an LLM router works in simple terms">Explain an LLM router</button><button data-prompt="Design a production architecture for an AI SaaS">Design an AI SaaS architecture</button><button data-prompt="Write a Python function with tests">Write Python + tests</button><button data-prompt="Analyze the advantages of automatic model failover">Analyze model failover</button></div></div>'}
function newChat(){messages=[];activeChatId=null;lastPrompt='';chat.innerHTML=welcome();bindSuggestions();closeMenu();input.focus()}
function bindSuggestions(){document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{input.value=b.dataset.prompt;submit()})}
async function persist(){if(!messages.length)return;const title=(messages.find(x=>x.role==='user')?.content||'New chat').slice(0,80);const r=await fetch('/api/conversations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:activeChatId,title,messages})});if(r.ok){const d=await r.json();activeChatId=d.id;const item={id:d.id,title,messages:[...messages]};const i=chats.findIndex(c=>c.id===d.id);if(i>=0)chats[i]=item;else chats.unshift(item);save();renderHistory()}}
async function submit(){const text=input.value.trim();if(!text||send.disabled)return;lastPrompt=text;input.value='';resize();messages.push({role:'user',content:text});addMessage('user',text);const row=addMessage('assistant','Thinking…'),bubble=row.querySelector('.message');send.disabled=true;send.classList.add('loading');const started=performance.now();try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversation_id:activeChatId,messages,model:window.selectedModel||null,stream:true})});if(!r.ok){const data=await r.json().catch(()=>({}));throw new Error(data.error||'Router request failed')}if(!r.body)throw new Error('Streaming is not supported by this browser');const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='',answer='',meta={};const consume=chunk=>{buffer+=chunk;const parts=buffer.split('\n\n');buffer=parts.pop()||'';for(const part of parts){const line=part.split('\n').find(x=>x.startsWith('data:'));if(!line)continue;const raw=line.slice(5).trim();if(raw==='[DONE]')continue;let event;try{event=JSON.parse(raw)}catch(e){continue}if(event.type==='delta'){answer+=event.content||'';bubble.innerHTML=renderText(answer);chat.scrollTop=chat.scrollHeight}if(event.type==='usage')meta.usage=event.usage;if(event.model)meta.model=event.model;if(event.provider)meta.provider=event.provider;if(event.type==='error')throw new Error(event.error||'Streaming request failed')}};while(true){const {value,done}=await reader.read();if(done)break;consume(decoder.decode(value,{stream:true}))}consume(decoder.decode());if(!answer)throw new Error('No response returned.');messages.push({role:'assistant',content:answer});$('#latency').textContent=`${Math.round(performance.now()-started)} ms · ${meta.provider||'auto'} · ${meta.model||'router'}`;await persist()}catch(e){const msg=`Router error: ${e.message}`;bubble.textContent=msg;if(messages[messages.length-1]?.role==='user')messages.push({role:'assistant',content:msg})}finally{send.disabled=false;send.classList.remove('loading');input.focus()}}
function deleteChat(id){chats=chats.filter(c=>c.id!==id);save();fetch('/api/conversations/'+encodeURIComponent(id),{method:'DELETE'}).catch(()=>{});if(activeChatId===id)newChat();renderHistory()}
function resize(){input.style.height='auto';input.style.height=Math.min(input.scrollHeight,180)+'px'}function closeMenu(){$('#modelMenu').classList.remove('open');$('#sidebar').classList.remove('open')}
async function status(){try{const d=await (await fetch('/api/status')).json();const p=$('#statusPill');p.classList.add('ok');p.querySelector('span').textContent=`${d.providers.length} provider${d.providers.length===1?'':'s'} configured`;const menu=$('#modelMenu');menu.innerHTML='<button class="model-option" data-model=""><span>Auto Router</span><span>recommended</span></button>';d.providers.forEach(x=>(x.models||[]).forEach(m=>{const b=document.createElement('button');b.className='model-option';b.dataset.model=m;b.innerHTML=`<span>${esc(m)}</span><span>${esc(x.provider)}</span>`;menu.appendChild(b)}));menu.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{window.selectedModel=b.dataset.model;$('#modelName').textContent=b.dataset.model||'Auto Router';closeMenu()});window.routerStatus=d}catch(e){$('#statusPill').querySelector('span').textContent='Offline / configure keys'}}
async function settings(){const d=window.routerStatus||{providers:[]};let a={};try{a=await (await fetch('/api/analytics')).json()}catch(e){}$('#settingsContent').innerHTML=`<div class="stats"><div><b>${a.requests||0}</b><small>requests / 24h</small></div><div><b>${a.success_rate||0}%</b><small>success rate</small></div><div><b>${a.avg_latency_ms||0} ms</b><small>avg latency</small></div></div><h3>Providers</h3><div class="provider"><span>Web API</span><small>${esc(location.origin)}</small></div>${d.providers.map(p=>`<div class="provider"><span><i class="provider-dot ${p.available?'on':''}"></i>${esc(p.provider)}</span><small>${p.available?'available':'cooldown'} · ${p.day_tokens||0} tokens today</small></div>`).join('')||'<p>No providers configured. Add API keys to .env.</p>'}`;$('#settingsModal').classList.add('open')}
$('#composer').onsubmit=e=>{e.preventDefault();submit()};input.oninput=resize;input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}};$('#newChat').onclick=newChat;$('#clearBtn').onclick=newChat;$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#modelBtn').onclick=()=>$('#modelMenu').classList.toggle('open');$('#settingsBtn').onclick=settings;$('#closeSettings').onclick=()=>$('#settingsModal').classList.remove('open');$('#themeBtn').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem('router_theme',document.documentElement.classList.contains('light')?'light':'dark')};chat.addEventListener('click',e=>{if(e.target.dataset.copy){const t=e.target.closest('.message-row').querySelector('.message').innerText;navigator.clipboard?.writeText(t);e.target.textContent='Copied';setTimeout(()=>e.target.textContent='Copy',1000)}if(e.target.dataset.copyCode)navigator.clipboard?.writeText(e.target.closest('pre').innerText.replace(/^Copy\n/,''));if(e.target.dataset.retry){input.value=lastPrompt;submit()}});if(localStorage.getItem('router_theme')==='light')document.documentElement.classList.add('light');try{chats=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){chats=[]}renderHistory();status();newChat();
